version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/songs
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - song-data:/data/db

volumes:
  song-data: