version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:${PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - song-data:/data/db

volumes:
  song-data: